INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㄱㅌ', '곰탕', '고기와 국물이 푸짐한 음식');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㄱㅈ', '계절', '봄, 여름, 가을, 겨울 중 하나');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅅㅇ', '서양', '동양과 대조되는 서쪽의 지역');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅈㅂㅈ', '전복죽', '전복이 들어간 부드러운 죽');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㄱㅈ', '계절', '봄, 여름, 가을, 겨울 중 하나');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅅㄱㅌ', '삼계탕', '닭고기와 죽순이 들어간 건강식');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅇㅂㅅ', '이발소', '머리를 자르고 다듬는 곳');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㄹㄷㄷㅌ', '롯데타워', '한국의 대표적인 높은 건물');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅁㄹ', '물류', '상품을 움직이고 보관하는 일련의 과정');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅇㄱ', '응급', '급하게 처리해야 하는 상황이나 의료 서비스');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㄷㄹ', '달력', '날짜와 시간을 표시하는 시스템');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅇㅅ', '일식', '일본의 전통 음식');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㄱㄱㅂ', '광고물', '상품이나 서비스를 홍보하는 자료');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅇㄷ', '의도', '계획이나 목적을 가지고 하는 행동');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅇㄹ', '여론', '대중의 의견이나 감정');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㄱㄹ', '국립', '국가가 소유하거나 관리하는 것');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅇㄴ', '인내', '어려운 상황이나 고통을 참고 견뎌내는 것');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㄷㅇ', '도약', '높은 곳에서 떨어져 나가는 행동');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅅㄱ', '생각', '의식적이거나 무의식적인 사고');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㄹㅂ', '로봇', '인간의 일을 자동적으로 수행하는 기계');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅅㅂ', '수박', '여름철에 주로 먹는 큰 과일');
INSERT INTO quiz (initial_word, answer, explanation) VALUES ('ㅁㅇ', '무역', '상품이나 서비스를 교환하는 거래');
